### ISSUE TITLE
Change state view in Admin dashboard is crashing

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/scholarx#157]
**Describe the bug**
The front end crashes when visiting the change state view in the deployed version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://sef-scholarx.herokuapp.com/
2. Click on 'the manage button of an application
4. See the error

**Expected behaviour**
The dashboard should load without an issue

**Screenshots**
![Kapture 2021-06-05 at 13 58 24](https://user-images.githubusercontent.com/33048395/120885682-c5c49e80-c607-11eb-937e-45eed7a2c93a.gif)

**Log**
```
bundle.js:305 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Ko (bundle.js:305)
    at t.useState (bundle.js:297)
    at my (bundle.js:321)
    at $o (bundle.js:305)
    at gl (bundle.js:305)
    at cs (bundle.js:305)
    at ls (bundle.js:305)
    at Ql (bundle.js:305)
    at bundle.js:305
    at t.unstable_runWithPriority (bundle.js:313)
nl @ bundle.js:305
bundle.js:305 TypeError: Cannot read property 'removeChild' of null
    at o.value (bundle.js:8)
    at o.value (bundle.js:8)
    at bundle.js:305
    at il (bundle.js:305)
    at ul (bundle.js:305)
    at fs (bundle.js:305)
    at t.unstable_runWithPriority (bundle.js:313)
    at Wr (bundle.js:305)
    at ps (bundle.js:305)
    at Ql (bundle.js:305)
nl @ bundle.js:305
bundle.js:305 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ul (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:86650)
    at fs (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:99857)
    at t.unstable_runWithPriority (https://sef-scholarx.herokuapp.com/dist/bundle.js:313:3844)
    at Wr (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:45023)
    at ps (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:97717)
    at Ql (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:93871)
    at https://sef-scholarx.herokuapp.com/dist/bundle.js:305:45314
    at t.unstable_runWithPriority (https://sef-scholarx.herokuapp.com/dist/bundle.js:313:3844)
    at Wr (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:45023)
    at Kr (https://sef-scholarx.herokuapp.com/dist/bundle.js:305:45259)
nl @ bundle.js:305
bundle.js:305 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Ko (bundle.js:305)
    at t.useState (bundle.js:297)
    at my (bundle.js:321)
    at $o (bundle.js:305)
    at gl (bundle.js:305)
    at cs (bundle.js:305)
    at ls (bundle.js:305)
    at Ql (bundle.js:305)
    at bundle.js:305
    at t.unstable_runWithPriority (bundle.js:313)
nl @ bundle.js:305
bundle.js:313 Uncaught TypeError: Cannot read property 'removeChild' of null
    at o.value (bundle.js:8)
    at o.value (bundle.js:8)
    at bundle.js:305
    at il (bundle.js:305)
    at ul (bundle.js:305)
    at fs (bundle.js:305)
    at t.unstable_runWithPriority (bundle.js:313)
    at Wr (bundle.js:305)
    at ps (bundle.js:305)
    at Ql (bundle.js:305)
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.4472.77 (Official Build) (arm64)

**Comment by sefglobal** [comment]
This issue has been mentioned on **SEF Hive**. There might be relevant details there:

https://sef.discourse.group/t/admin-flow-scholarx/280/7

**Comment by anjula-sack** [comment]
This issue had been fixed with this PR
https://github.com/sef-global/scholarx/pull/159
